### PR TITLE
Stable rust

### PR DESCRIPTION
**Pull request by sajattack**
This PR is able to build all boards except metro_m0 and samd21_mini (because rtfm) on stable rust.

### CODE REVIEW

**Comment by wez** [comment]
https://github.com/atsamd-rs/atsamd/commit/2e4e9fff1117356aba07729aeb5198f155901a18 fixes up a couple of issues.  I'm looking at the rtfm side of this now.

You'll want to regenerate the pacs again; I pushed some padding fixes to my svd2rust tree (see https://github.com/rust-embedded/svd2rust/issues/230#issuecomment-451362856)

**Comment by wez** [comment]
I've pushed some commits to https://github.com/atsamd-rs/atsamd/tree/wez-stable-rust that fixup a few things; can you give those a try on real hardware and cherry pick them into your PR?

**Comment by sajattack** [comment]
I don't have a metro m0.

**Comment by wez** [comment]
testing on any real hardware will do; everything builds now, just want to make sure it actually runs on some real hardware

**Comment by sajattack** [comment]
I just realized we forgot version bumps for pac and hal.

**Comment by sajattack** [comment]
My cpx blinks, I don't see how that verifies the rtfm changes but oh well, it's up to you.

**Comment by sajattack** [comment]
Oopsie, forgot to update the dependencies to get the new version.

**Pull request merged**
