### PR TITLE
Adds convenience UART setup to PyPortal

### PR DESCRIPTION
**Pull request by fionawhim**
UART is hardwired to the ESP32 Wi-Fi co-processor.

### CODE REVIEW

**Comment by sajattack** [comment]
Hmm, maybe we should rename it esp_tx esp_rx esp_uart?

**Comment by fionawhim** [comment]
That works for me. I can edit the pull request.

**Comment by fionawhim** [comment]
@sajattack all set!

**Comment by fionawhim** [comment]
I think my language server crashed and I didn’t notice, hence no red in my IDE. 🤦‍♀ 

Fixed now, and verified with local build.

**Pull request merged**
