### PR TITLE
Feather M0 USB Example

### PR DESCRIPTION
**Pull request by tekulvw**
Copied the example from itsybitsy, got code hooked together, added new deps and have a working echo!

### CODE REVIEW

**Comment by twitchyliquid64** [comment]
Nice! Could you update the `.travis.yaml` [here](https://github.com/atsamd-rs/atsamd/blob/master/.travis.yml#L12) so it compiles the example + compiles with the `usb` feature? That way travis can will fail if the example breaks compilation.

**Comment by sajattack** [comment]
@tekulvw could you rebase this on master please?

**Comment by WyseNynja** [comment]
What can I run on the host machine to test this?

**Comment by twitchyliquid64** [comment]
The device emulates a serial port: you should be able to open it and have it echo back characters

**Pull request merged**
