### PR TITLE
Upgrades to digital::v2 GPIO interface

### PR DESCRIPTION
**Pull request by fionawhim**
New interface returns a Result, old interface was deprecated.

Fixes atsamd-rs/atsamd#69

### CODE REVIEW

**Comment by sajattack** [comment]
It's generally bad practice to have unwraps in a library. Also I wonder if it's possible through one of the _compat modules of the digital module to keep the old interface exposed as well as the new one, and reduce the need to change every program that's ever used a digital pin.

**Comment by fionawhim** [comment]
It’s your call re: the `unwrap`s. I suppose they could be switched to `ok`s, we just need to consume the `Result`.

It *may* be the case that we could switch from `()` as the `Error` type to `Infallible`, and use an exhaustive `match` on the result in the library, which would (from what I understand) let us not include the `Err` option since `Infallible` is an enum with no choices. That way, if we ever added an `Error` to the pins that did something, there would be a compile error that the match wasn’t exhaustive that would tell us to handle it in the library code.

I don’t think we can easily expose both interfaces at the same time, because they have the same method names. So if our pins had both traits, I think consumers would need to specify which `set_high` implementation to use, which would be a lot of boilerplate.

Fixing the broken pyportal example now. It was missing an `into`.

**Comment by sajattack** [comment]
Unwraps are fine for examples. Can you change the ones in `lib.rs`to tries maybe?

**Comment by fionawhim** [comment]
@sajattack My understanding is that that would mean changing all of the `flash_spi_master` _&c._ functions to return `Result`s. If we did that, we could also remove the `unwrap`s that are already in there for getting the SERCOM clocks.

Is that what you’d like?

**Comment by sajattack** [comment]
I think that's probably best practice but I'd like to see if anyone else has other ideas.

**Comment by sajattack** [comment]
I guess unwraps might be less hassle for the end-user, and no one has gotten back to me on whether that is egregiously bad practice so f*** it I guess. You ready?

**Comment by tarcieri** [comment]
IMO `unwrap()` is fine in cases where you are completely confident they will never fail, which per the comments appears to be the case here.

I use `expect()` in cases which are more like "well it's not panicking in the tests, but I'm not completely sure this scenario will be panic-free"

**Comment by fionawhim** [comment]
@sajattack Cool. I think this is ready for merge, then.

**Pull request merged**
