### PR TITLE
Add sercom3 spi layout

### PR DESCRIPTION
**Pull request by NickeZ**
I had to add this to compile my project. Is this correct?

### CODE REVIEW

**Comment by sajattack** [comment]
Unfortunately this dipo/dopo business is part of the datasheet I never understood. @wez might be able to take a look at it, but he's usually pretty busy. Also, there's another PR in touching this part of sercoms that will probably conflict with yours.

**Comment by keithduncan** [comment]
I took a look at the `SAM D5x/E5x Family Data Sheet` for these values, in the copy I have a DOPO value of `0x1` is reserved. It doesn’t look possible to map Data In to pad 2 and Data Out to pad 1 with Clock on pad 0.

@NickeZ can I check what pad mapping you’re trying to create? I’ve opened https://github.com/atsamd-rs/atsamd/pull/61 to add type states for all the pad mapping combinations so I want to make sure I’ve gotten it right there too 😄

**Comment by NickeZ** [comment]
Below is the mapping I have. This code works, but I'm definitely new to embedded rust so my problem could definitely be somewhere else.

```c
#define PIN_SPI_CLK  GPIO(GPIO_PORTA, 16)
#define PIN_SPI_MOSI GPIO(GPIO_PORTA, 17)
#define PIN_SPI_MISO GPIO(GPIO_PORTA, 18)
```

**Comment by keithduncan** [comment]
Thanks!

Have you done bidirectional SPI with this code? Which sercom are you multiplexing the pins you’ve shown into? Did you get this pad and pin mapping from a data sheet or construct it on a board you have?

**Comment by NickeZ** [comment]
Good questions. I don't think it is bidirectional actually, we use it for communicating with an oled display. It is on an in-house board. It is sercom3.

**Comment by keithduncan** [comment]
Can I check which chip model/revision you’re using? The [SAM D51 datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/60001507C.pdf) pg 1001 doesn’t define DOPO 1 🤔

**Comment by NickeZ** [comment]
Looking a bit closer at it, it should map like this:

```c
// CLK
#define PIN_SPI_CLK  GPIO(GPIO_PORTA, 16) // SERCOM3_PAD1
// MOSI
#define PIN_SPI_MOSI GPIO(GPIO_PORTA, 17) // SERCOM3_PAD0
// MISO
#define PIN_SPI_MISO GPIO(GPIO_PORTA, 18) // SERCOM3_PAD2
```

Which I guess is:

```rust
        hal::sercom::SPI3Pinout::Dipo2Dopo0 {
            miso: miso.into_pad(port),
            mosi: mosi.into_pad(port),
            sck: sck.into_pad(port),
        },
```

But then I guess this compiler error:

```
$ cargo build
   Compiling bitbox02-board v0.1.0 (/home/niklas/projects/shift/bitbox02-firmware-rust-2/bitbox02-board)
error[E0277]: the trait bound `hal::gpio::Pa17<hal::gpio::Input<hal::gpio::Floating>>: hal::sercom::PadPin<hal::sercom::Sercom3Pad0>` is not satisfied
  --> bitbox02-board/src/lib.rs:99:24
   |
99 |             mosi: mosi.into_pad(port),
   |                        ^^^^^^^^ the trait `hal::sercom::PadPin<hal::sercom::Sercom3Pad0>` is not implemented for `hal::gpio::Pa17<hal::gpio::Input<hal::gpio::Floating>>`
   |
   = help: the following implementations were found:
             <hal::gpio::Pa17<MODE> as hal::sercom::PadPin<hal::sercom::Sercom1Pad1>>
             <hal::gpio::Pa17<MODE> as hal::sercom::PadPin<hal::sercom::Sercom3Pad1>>

error[E0277]: the trait bound `hal::gpio::Pa16<hal::gpio::Input<hal::gpio::Floating>>: hal::sercom::PadPin<hal::sercom::Sercom3Pad1>` is not satisfied
   --> bitbox02-board/src/lib.rs:100:22
    |
100 |             sck: sck.into_pad(port),
    |                      ^^^^^^^^ the trait `hal::sercom::PadPin<hal::sercom::Sercom3Pad1>` is not implemented for `hal::gpio::Pa16<hal::gpio::Input<hal::gpio::Floating>>`
    |
    = help: the following implementations were found:
              <hal::gpio::Pa16<MODE> as hal::sercom::PadPin<hal::sercom::Sercom1Pad0>>
              <hal::gpio::Pa16<MODE> as hal::sercom::PadPin<hal::sercom::Sercom3Pad0>>

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `bitbox02-board`.

To learn more, run the command again with --verbose.
```

**Comment by NickeZ** [comment]
There seems to be [a newer SVD](http://packs.download.atmel.com/) for this chip with the following release notes:

> 1.2.139 (2019-04-09) | Fix: Modes in SVD, Value-group for USER_FUSES, define in GCLK. Added python programming and debugging scripts for MPLAB X.

However, svd2rust panics on it:

```
$ RUST_BACKTRACE=1 svd2rust -i svd/ATSAMD51J20A.svd
thread 'main' panicked at '/home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/svd-parser-0.6.0/src/lib.rs:60 c.text.clone()', src/libcore/option.rs:1034:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::option::expect_failed
             at src/libcore/option.rs:1034
   9: svd_parser::cluster_register_parse
  10: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  11: svd_parser::Peripheral::parse
  12: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  13: svd_parser::Device::parse
  14: svd_parser::parse
  15: svd2rust::main
  16: std::rt::lang_start::{{closure}}
  17: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  18: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  19: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  20: main
  21: __libc_start_main
  22: _start
```

**Comment by NickeZ** [comment]
That panic was fixed by a `sed -i 's/<description\/>/<description>test<\/description>/g'` (modulo any typos, I did it in vim).

**Comment by NickeZ** [comment]
Sorry I didn't answer your question before

> Can I check which chip model/revision you’re using? The SAM D51 datasheet pg 1001 doesn’t define DOPO 1 thinking

We have the following chip: atsamd51j20a

**Comment by NickeZ** [comment]
I took a closer look at the datasheet and I think I found the issue in the hal. For sercom3 the pins are switched compared to sercom1. Please see attached screenshot of datasheet.
sercom3

**Comment by keithduncan** [comment]
This looks correct to me, you’re right these were backwards in the sercom 3 pad enums and the pin -> functionality you’re using matches the Dipo2Dopo0 pad configuration :+1: Good find 😄

**Comment by NickeZ** [comment]
I've tested this configuration on real hardware as well, and it works as expected! :tada:

**Comment by sajattack** [comment]
Does this conflict at all with your pr @keithduncan? Should we try to combine the two?

**Comment by keithduncan** [comment]
It does, I’ve pushed up a merge in https://github.com/atsamd-rs/atsamd/pull/61/commits/ba746c3d720292972c53ee8f6875483d26ab65ae so these can land in any order.

**Comment by sajattack** [comment]
Merged into #61

**Pull request closed without merging**
