### PR TITLE
update smart-leds, remove wheel function for smart_leds hsv conversion (non pygamer boards only)

### PR DESCRIPTION
**Pull request by jacobrosenthal**
More  #123

Could probably use a spot check on these boards as I dont own them.

### CODE REVIEW

**Comment by sajattack** [comment]
I'll try my Metro M4 when I'm back from Christmas holidays, we might want to switch to a different ws2812 impl than the nop one.

**Comment by tarcieri** [comment]
I can try the Trellis M4 when I'm back from the Christmas holidays as well

**Comment by sajattack** [comment]
SpinTimer is similar to nop but works better.

**Comment by jacobrosenthal** [comment]
Yeah Ive consolidated on the spintimer for all my pygamer examples

**Comment by jacobrosenthal** [comment]
Ping on this in case anyone is back from holidays.

**Comment by sajattack** [comment]
Pygamer build failed.

**Comment by jacobrosenthal** [comment]
Thanks for the ping. Fixed now

**Comment by sajattack** [comment]
Neopixels not working on metro m4.

**Comment by jacobrosenthal** [comment]
and to confirm, upstream master did work.

**Comment by jacobrosenthal** [comment]
Oh pygamer is on newest version of of smartleds using ws2812 timer (without
slow) and with lto re-enabled. I found this to be far more stable on
pygamer. Ill push an update for trellis and metro m4 since thats what this
touches.

**Comment by sajattack** [comment]
Not sure if it was working lately, it's probably lto and stuff breaking nop, SpinTimer is preferable.

**Comment by sajattack** [comment]
Now rainbow works and blink doesn't.

**Comment by jacobrosenthal** [comment]
Im not sure, I can peel off those commits or maybe you can take a look. Im not partial to any of these changes, especially if it blocks this merge. Im just trying to get the offer the other boards the cleanups Ive been doing in pygamer.

**Comment by jacobrosenthal** [comment]
Note, The sodaq_one, metro_m0 and feather_m0 are still lto=false for debug only

Is there a reason to update those as well? And or, should we be using lto=false for debug?

**Comment by sajattack** [comment]
Well, the m0 boards can't use spintimer, so might be best to leave those.

**Comment by sajattack** [comment]
I'll try to fix neopixel blink and if I can't we might as well delete it.

**Comment by jacobrosenthal** [comment]
Yeah I was hoping to avoid those boards as I cant confirm a best path for them. However, when I looked, I didnt find an m0 board here that has neopixel examples anyway? I think people are just copy pasting the lto settings from other boards

**Comment by jacobrosenthal** [comment]
Metro m4 neopixel blink has a TimerCounter going in it for no reason.. that could be removed too

**Comment by sajattack** [comment]
Yes I see that and am deleting it.

**Comment by sajattack** [comment]
@tarcieri you around to try your boards?

**Comment by tarcieri** [comment]
I am around but my boards are thousands of miles away. I can check in a week.

**Comment by jacobrosenthal** [comment]
@tarcieri ping check those boards?

**Comment by tarcieri** [comment]
I fly home today and can check very soon!

**Comment by jacobrosenthal** [comment]
Another friendly ping :)

**Comment by sajattack** [comment]
@tarcieri ping

**Comment by tarcieri** [comment]
sorry about the delay! will check tomorrow

**Comment by sajattack** [comment]
@jacobrosenthal, it looks like the unnecessary timer on metro m4 snuck back in.

**Comment by jacobrosenthal** [comment]
Got it, thanks

**Comment by tarcieri** [comment]
Just tried this out on the Trellis M4 and I can't get it working in either debug or release mode.

The resulting `neopixel_rainbow.bin` seems significantly larger than it used to be (~200kB instead of 20kB).

If I go back a bit before this PR though, the binaries are over 1MB (and therefore unflashable).

I was able to build from the last known working release (`trellis_m4` v0.1.2) and that works. I suppose I can try to bisect...

**Comment by sajattack** [comment]
I think there's something weird with your setup. I run `arm-none-eabi-size` on neopixel_rainbow and it reports 1832 bytes.

**Comment by tarcieri** [comment]
Seems I was missing the `-O binary` flag on `arm-none-eabi-objcopy`

After adding that it appears to be working! 🎉

**Pull request merged**
