### PR TITLE
Update bitflags and remove `TryFrom<()>` impls

### PR DESCRIPTION
**Pull request by jbeaurivage**
# Summary
The `TryFrom<()>` impls are a bit of a weird construct, and they now trigger build failures on nightly. By the same occasion also update bitflags and fix some bugs preventing the USB peripheral from building for SAMD11 targets.

# Checklist
  - [ ] ~~`CHANGELOG.md` for the BSP or HAL updated~~ Not necessary - all changes are internal APIs only
  - [x] All new or modified code is well documented, especially public items
  - [x] No new warnings or clippy suggestions have been introduced

### CODE REVIEW

**Comment by jbeaurivage** [comment]
@ianrrees this may help getting CI green again :)

**Comment by ianrrees** [comment]
Cheers!  Yeah I've done the same thing with the bitflags just was waiting until we had the CI thing sorted to PR.

Minor suggestion - could we put the english name of the flags in the docstrings, eg `ISF` to `ISF - Inconsistent Sync Field`?

**Comment by jbeaurivage** [comment]
> Cheers! Yeah I've done the same thing with the bitflags just was waiting until we had the CI thing sorted to PR.
> 
> Minor suggestion - could we put the english name of the flags in the docstrings, eg `ISF` to `ISF - Inconsistent Sync Field`?

Done!

**Comment by ianrrees** [comment]
Hmm, I guess GitHub isn't quite clever enough to detect that I merged this locally.  Hope you still get the GitHub points @jbeaurivage !

**Pull request closed without merging**
