### PR TITLE
Upgrade embedded-graphics to 0.5, st7735-lcd to 0.6

### PR DESCRIPTION
**Pull request by johnbatty**
Move pygamer up to a newer version of embedded-graphics.
This also requires upgrading the st7735-lcd driver.

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
Ive personally been waiting for .6 which is around the corner and has a ton more breaking changes. However its been around the corner for quite some time so Im fine with this. Can you upgrade all the bsps though?

**Comment by johnbatty** [comment]
Ok - I'll work on updating the other BSPs.  Looks like it is just `edgebadge` and `itsybitsy_m0` that use `embedded-graphics` and are currently on 0.4.  `feather_m0` also uses it, but is already on 0.6.0-alpha.

**Comment by jacobrosenthal** [comment]
eg 0.6 beta1 is out with more breaking changes, but Ive heard it said there shouldnt be much more breaking after this so a good time to go straight to that

Im still keeping my work up to date with beta at 
https://github.com/jacobrosenthal/atsamd/tree/embedded-graphics-0.6
https://github.com/jacobrosenthal/st7735-lcd-rs/tree/0.6

Theyre working on migration guide
https://github.com/jamwaffles/embedded-graphics/pull/255

**Comment by jamwaffles** [comment]
>  Ive heard it said there shouldnt be much more breaking after this so a good time to go straight to that

Yep, bar any horrific crap we've missed this should remain true until 0.6.0 proper.

> Theyre working on migration guide

I am indeed, please comment on that PR if there's anything you want to see in it, even though it's still WIP.

**Comment by jacobrosenthal** [comment]
@johnbatty are you still able to refresh pr?

**Comment by jacobrosenthal** [comment]
Ive got the pygamer and edgebadge done here, i can pr into here or make fresh
https://github.com/jacobrosenthal/atsamd/tree/embedded-graphics-0.6

**Pull request closed without merging**
