### PR TITLE
Fix text baseline broken in recent version bump

### PR DESCRIPTION
**Pull request by cbiffle**
As I noted in #603, PR #591 bumped a bunch of crates across what are
effectively major version boundaries, because the crates are in the
leading-zero phase of semver -- so an 0.6 to 0.7 update is breaking.
This has broken _at least_ text rendering.

This commit fixes the text baseline calculations to use the method
expected by the embedded-graphics 0.7 crate, which has (quite
reasonably) switched to using baselines instead of bounding box top to
place text, but opted to leave the old implicit-baseline `new` operation
in place and change its behavior, which allowed all of this to break
without any compile errors.

NOTE THAT WITH THIS COMMIT NEARLY ALL OF THE WIO TERMINAL DEMOS ARE
STILL BADLY BROKEN. I'm new here and I'm not sure if these worked before
the version bump, or if they were also broken by the merge of this
untested PR, but at this point, only clock and usb_serial_display work.
Everything else displays blinking garbage on the display and hangs.

# Summary
[describe your changes here]

# Checklist
  - [ ] `CHANGELOG.md` for the BSP or HAL updated
  - [ ] All new or modified code is well documented, especially public items
  - [ ] No new warnings or clippy suggestions have been introduced (see CI or check locally)

## If Adding a new Board
  - [ ] Board CI added to `crates.json`
  - [ ] Board is properly following "Tier 2" conventions, unless otherwise decided to be "Tier 1"

### CODE REVIEW

**Comment by cbiffle** [comment]
To partially answer my own question: I've rewound past the version bump commit to the commits preparing for the 0.15 release, and to the 0.14 release, and the Wio Terminal examples were already broken, though the screen garbage looks different than after the version bump. So, that commit is off the hook for part of the breakage.

**Comment by sajattack** [comment]
@jessebraham @twitchyliquid64 this is what happens when you leave your boards unattended :stuck_out_tongue:

**Comment by cbiffle** [comment]
FWIW it turns out some of the display corruption is because the graphics examples have, for some time, been attempting to clear a 320 x 320 screen; the Wio Terminal's screen is 320 x 240. It looks like the behavior of this changed recently somewhere in the web of dependencies. Fixing the screen sizes for e.g. the qspi example causes it to at least correctly clear the screen, though it still doesn't work.

**Comment by cbiffle** [comment]
And just in case anyone's riveted by these updates: so it turns out you can get the qspi example display updates to work by _raising the display clock frequency_ to 58 MHz, which I tried because it's the speed used by `usb_serial_display`, one of the demos that worked.

With that and the display size fix, the qspi demo on master works.

I assume the qspi demo did work at some point, so, not sure what changed. Maybe your clock setup code can't achieve 24 MHz exactly and its fallback behavior is different than it used to be?

**Comment by cbiffle** [comment]
Aaand fwiw, with the display clock change to 58, all of the demos work on a newly unboxed Wio Terminal _except_ the wifi ones, which hang.

The sdcard demo begins by drawing on an uninitialized display, so the first pass tends to look like garbage, but after 2.5 seconds it clears the screen properly and tries again.

So, I conclude that something is wrong with the clock setup routine.

**Comment by TDHolmes** [comment]
@cbiffle , thanks for looking into all of this. Do you want to pull in any more of these changes into this PR, or keep it to just the text baseline change?

**Comment by cbiffle** [comment]
Thanks for asking! No, I'm really hesitant to offer any fixes when I don't understand the problem. After you find a working clock frequency, nudging it up or down by 1MHz can cause the display driver to hang, which seems... suspicious.

**Comment by TDHolmes** [comment]
Lol agreed, quite sus. We can just take this for now then.

**Comment by pabigot** [comment]
@cbiffle Thanks for your diagnosis and fix.  I've rebased this on current master, added the fix in https://github.com/atsamd-rs/atsamd/pull/604#issuecomment-1099736323, and done one more in [my main](/pabigot/atsamd/tree/pabmain).  Now I'm just down to wifi making the wio act like a brick.

**Pull request merged**
