### PR TITLE
add feather_m0 pins d3, d4, d8

### PR DESCRIPTION
**Pull request by WyseNynja**
I have a feather_m0 LoRa and it uses pins 3, 4, and 8 for the Lora Module Control: https://learn.adafruit.com/assets/46254

I haven't yet tested this on actual hardware, but I'm pretty sure it is correct since it matches adafruit's pinout diagram.

### CODE REVIEW

**Comment by sajattack** [comment]
My feather m0 doesn't have these pins exposed.

**Comment by WyseNynja** [comment]
Yeah, not all of them do. I also have adafruit's feather m0 basic proto and it doesn't expose them: https://learn.adafruit.com/assets/46244

Should these maybe be behind a feature?

**Comment by rubberduck203** [comment]
I feel like it would be good to put them behind a feature.

**Comment by sajattack** [comment]
I'm not sure if that's possible with our current macro for pins.

**Comment by TDHolmes** [comment]
I don't see the harm in having the "superset" of feather_m0 pins 🤷🏼‍♂️ Might as well keep it simple and have the superset, so long as nothing collides.

**Comment by WyseNynja** [comment]
I could add a comment saying something like "not exposed on all models"


Bryan

**Comment by sajattack** [comment]
I suppose that's reasonable, but some people might feel like it violates rust's safety guidelines.

**Comment by WyseNynja** [comment]
Is using a non-existent pin actually unsafe?

I need these pins for my project, but features aren't an option. So what's the alternative?

**Comment by TDHolmes** [comment]
Agreed. A pin will toggle on a disconnected pin of the micro. Seems fine to
me.

**Comment by sajattack** [comment]
Yeah I guess it's the best we can do. Please add a comment at least.

**Comment by rubberduck203** [comment]
> I'm not sure if that's possible with our current macro for pins.

@sakattack what makes you unsure? Has anyone tried?

**Comment by sajattack** [comment]
@rubberduck203 macros require fixed tokens for syntax and I don't think #[cfg(feature="whatever")] would be part of the macro without modification.

**Comment by jessebraham** [comment]
I had to modify `pin!()` recently to accept `#[cfg()]`, it's not too difficult. See lines `16` and `36` here:
https://github.com/jessebraham/atsamd/blob/8812146ab697d769e52f4383b821810a6d3e18d6/hal/src/common/pad.rs

**Comment by jessebraham** [comment]
While working on an unrelated task I noticed that `define_pins` does seem to support feature gating:
https://github.com/atsamd-rs/atsamd/blob/master/hal/src/common/thumbv6m/gpio.rs#L569-L602

Reformatting the macro arguments makes this a bit more clear:

```rust
#[macro_export]
macro_rules! define_pins {
    (
        $(#[$topattr:meta])*
        struct $Type:ident,
        target_device: $target_device:ident,
        $(
            $(#[$attr:meta])*
            pin $name:ident = $pin_ident:ident
        ),+ ,
    ) => {

$crate::paste::item! {
    $(#[$topattr])*
    pub struct $Type {
        /// Opaque port reference
        pub port: Port,

        $(
            $(#[$attr])*
            pub $name: gpio::[<P $pin_ident>]<Input<Floating>>
        ),+
    }
}
```

Notice the `$(#[$attr:meta])*` and `$(#[$attr])*` for each pin definition. Anyways, just FYI.

**Comment by TDHolmes** [comment]
macro-confusion kind of makes this related to #214

**Comment by henrikssn** [comment]
I have the same problem for the RFM69 version of the Feather M0 board.

**Comment by ianrrees** [comment]
I've made https://github.com/atsamd-rs/atsamd/pull/319 , which adds these pins behind an "rfm" feature flag as suggested above

**Pull request closed without merging**
