### PR TITLE
Add free running ADC support to InterruptAdc

### PR DESCRIPTION
**Pull request by ciniml**
Hi. 

I'm currently implementing an application which uses ADC in free-run mode to acquire sensor outputs periodically.
And I've found that current `InterruptAdc` implementation does not support free-run mode at all.

So I want to add free-run mode support to `Adc` and  `InterruptAdc`.

I've added some functions to set `FREERUN` bit in the `CTRLB` register of the ADC peripheral to `Adc` struct.

I have a concern about the modification of `service_interrupt_ready` function.
I've removed `disable_interrupts`  and `power_down` calls from the `service_interrupt_ready` in order not to stop the ADC conversion after the first conversion and added `stop_conversion` function instead.
This changes the usage of `InterruptAdc` and may breaks applications which currently uses it.

Is API changes like this allowed? Or do I need to implement it as  another function?

### CODE REVIEW

**Comment by sajattack** [comment]
The InterruptAdc is a fairly new feature, so I don't think there will be too much existing code out there to break. I'm not too familiar with the different modes myself so I've asked a couple other people to weigh in on whether freerunning mode is a good default.

**Comment by sajattack** [comment]
It was suggested that another method be added for freerunning conversions to avoid breaking existing conversions.

**Comment by twitchyliquid64** [comment]
In general I don't think its a good idea to change the behavior of existing types, unless the change also causes a compile error for existing code (hence forcing existing usage to consider the change).

One idea: implement a new type parameter on InterruptAdc that describes how to handle the completion of a conversion.

Something like:

```rust
/// An ADC where results are accessible via interrupt servicing.
pub struct InterruptAdc<ADC, C>
where
  C: OnCompletion,
{
    adc: Adc<ADC>,
    m: PhantomData<C>,
}

/// Describes how an interrupt-driven ADC should finalize the peripheral
/// upon the completion of a conversion.
pub trait OnCompletion {
  fn on_complete(ADC);
}

pub struct FreeRunning;

impl OnCompletion for FreeRunning {
  fn on_complete() {
    // etc
  }
}
```

The method of instantiating the `InterruptAdc` will need to change too

But this way, the calling code gets to 'pick' the behavior, and the compiler will use the code from the underlying trait with no overhead :)

**Comment by ciniml** [comment]
Ok. Breaking existing API seems not to recommended according to the reply.

Now I've modified the code not to modifying existing `InterruptAdc` but adding `FreeRunAdc` , which does not stop ADC after first conversion.

The method suggested by @twitchyliquid64 seems elegant way.  But it requires changing existing `InterruptAdc` API, so it is difficult to do this.

**Comment by twitchyliquid64** [comment]
Sorry for the confusion - I think breaking behavior is okay **if the API also breaks as well**. So feel free to change the API.

**Comment by ciniml** [comment]
> Sorry for the confusion - I think breaking behavior is okay **if the API also breaks as well**. So feel free to change the API.

I see. I'll re-implement in the suggested way.

**Comment by ciniml** [comment]
I've implemented both single conversion mode and free-running mode in the `InterruptAdc`.

I've added `ConversionMode` trait to switch the procedure on `start_conversion`, `service_interrupt_ready` and `stop_conversion`.

**Comment by twitchyliquid64** [comment]
Looks great!

I'll get the CI fixed in #360, and then we should be good to make this go green :)

**Review by twitchyliquid64 — APPROVED** [review]
Just confirming before I merge that you've tested this?

**Comment by ciniml** [comment]
I've checked both SingleConversion and FreeRunning are working on my Seeed Wio Terminal.
Should I add some example code for the Wio Terminal BSP?

**Comment by twitchyliquid64** [comment]
If you have time that would be great :)

**Comment by ciniml** [comment]
Ok. I'll add examples for SimpleConversion and FreeRunning to Wio Terminal BSP.

**Comment by ciniml** [comment]
I've added `microphone` example to Wio Terminal BSP,  which continuously acquires sampled data of microphone via ADC1 and calculate and display min/max/avg.

**Comment by twitchyliquid64** [comment]
I love it, thank you so much for this and happy holidays!

**Pull request merged**
