### PR TITLE
Fix failing `bsp_pins!` invocation with no aliases

### LINKED ISSUE #599: bsp_pins! macro error when no pin definitions include aliases
Attempting to create a simple BSP for a custom PCB and had a problem using the `bsp_pins!` macro. When I omit `aliases: { ... }` from **all** my pin definitions, rust complains about "missing tokens in macro arguments." Adding an `aliases: { ... }` spec to any one or more pins clears the compiler error.

This code fails to compile:
```rust
...
pub mod pins {
    use super::hal;
    hal::bsp_pins!(
        PB12 { name: sca }
        PB13 { name: scl }
    );
}
```
Failing with,
```
error: unexpected end of macro invocation
  --> src/lib.rs:13:5
   |
13 | /     hal::bsp_pins!(
14 | |         PB12 { name: sca }
15 | |         PB13 { name: scl }
16 | |     );
   | |_____^ missing tokens in macro arguments
   |
   = note: this error originates in the macro `$crate::__define_pin_alias_macro` (in Nightly builds, run with -Z macro-backtrace for more info)
```

This code, however, compiles:

```rust
...
pub mod pins {
    use super::hal;
    hal::bsp_pins!(
        PB12 { name: sca }
        PB13 {
            name: scl
            aliases: {
                AlternateC: SCL
            }
        }
    );
}
```

Tested with **atsamd-hal 0.15.0** and **atsamd21j 0.12.0**.
**Rust stable 1.59.0**, but same error occurs in nightly.

I'm able to proceed using that workaround but it was awfully confusing at first.

### PR DESCRIPTION
**Pull request by bradleyharden**
When no aliases are included in a call of `bsp_pins!`, the resulting
`pin_alias!` macro expands to a completely empty macro definition, which
is invalid.

Add identity "aliases" for each given pin name. This has two benefits.
First, it prevents the empty macro case above. And second, it precludes
any possibility of collisions between names and aliases, since all names
are now checked before resolving aliases.

Closes #599

# Checklist
  - [x] `CHANGELOG.md` for the BSP or HAL updated
  - [x] All new or modified code is well documented, especially public items
  - [x] No new warnings or clippy suggestions have been introduced (see CI or check locally)

### CODE REVIEW

**Comment by TDHolmes** [comment]
Clever!

**Comment by bradleyharden** [comment]
Yes, I was waiting to hear from @datagrok, but I'm fairly confident it fixes the problem.

**Comment by bradleyharden** [comment]
This failed because of some strange rustup error, but I can't restart the job?

**Comment by datagrok** [comment]
Sorry for the delay. This does indeed fix the problem on my repo, @bradleyharden! Thanks!

**Pull request merged**
