### PR TITLE
Make wio_terminal display frequency consistent

### PR DESCRIPTION
**Pull request by pabigot**
58 MHz works on all examples.

### CODE REVIEW

**Comment by pabigot** [comment]
Some background adding on to https://github.com/atsamd-rs/atsamd/pull/604#issuecomment-1099634925:

Support for selecting display SPI speed was added in #320 (2020-11-15), where these were set to 58 MHz:

    buttons, clock, orientation, usb_serial_display

and these to 24 MHz:

    qspi, sdcard

possibly because they also use SPI for storage access.  These examples were added after #320:

    microphone, wifi_connect, wifi_scan

all of which picked 24 MHz.

The ILI9341 datasheet suggests that the maximum speed would be 10 MHz, but as noted in #320 as much as 80 MHz has been confirmed to work.

The display does not work for wifi_scan at 24 MHz; it does at 32 MHz, 40 MHz, and 58 MHz.  The other examples work at 58 MHz speed too, so make it consistent to reduce confusion in users creating new demos.

**Comment by jbeaurivage** [comment]
Could you please update the BSP's README?

**Comment by pabigot** [comment]
@jbeaurivage Rebased and README updated.  I'm not sure what you were looking for, let me know if this isn't it.

**Comment by jbeaurivage** [comment]
@pabigot sorry my mistake, I meant updating the changelog! But the info you put in the readme definitely doesn't hurt

**Comment by pabigot** [comment]
@jbeaurivage OK, that makes sense.  Should I add entries for my other recent fixes too?

**Comment by jbeaurivage** [comment]
Yes please! No worries, all the entries can be in this pr.

**Comment by pabigot** [comment]
@jbeaurivage done

**Comment by jbeaurivage** [comment]
Thanks for all the improvements @pabigot!

**Pull request merged**
