### PR TITLE
Fix typo in SPI interrupt register field

### PR DESCRIPTION
**Pull request by ianrrees**
Should be fairly self-explanatory ;)

### CODE REVIEW

**Comment by jbeaurivage** [comment]
Awesome! 

Looks like CI is failing because the BSP examples haven't been updated to the new RTIC alpha.

**Comment by bradleyharden** [comment]
@ianrrees, could you fix thumbv7em as well? And could you hardcode the RTIC version to alpha4? That should fix the tests. We can upgrade them later.

**Comment by bradleyharden** [comment]
@jacobrosenthal, this is probably the problem with #455

**Comment by ianrrees** [comment]
I've updated this PR for v7, but per matrix chat will make a new PR once we've figured out a fix for the RTIC example failures.

**Pull request merged**
