### PR TITLE
pygamer: remove wheel function for smart_leds hsv conversion

### LINKED ISSUE #111: neopixel rainbow examples cleanup
Love all your neopixel code and have been cargo culting it for pygamer as you can tell with all my noise in issues.

One more for @tarcieri @sajattack 
The wheel boiler plate were all using just feels too C for me, and I could barely understand it

```
const NUM_LEDS: usize = 5;
let mut data = [RGB8::default(); NUM_LEDS];

loop {
    for j in 0..(256 * 5) {
        for i in 0..NUM_LEDS {
            data[i] = wheel((((i * 256) as u16 / NUM_LEDS as u16 + j as u16) & 255) as u8);
        }
        let _ = neopixel.write(brightness(data.iter().cloned(), 32));
        delay.delay_ms(5u8);
    }
}
```

Im thinking of PRing a cleanup to all of us. Wondering if anyone has a preference. I got a huge win in just doing this I think
```
const NUM_LEDS: usize = 5;
let mut data = [RGB8::default(); NUM_LEDS];

loop {
    for j in 0..255u8 {
        for i in 0..NUM_LEDS {
            // stagger the color changes across all 5 leds evenly, 255/5=51
            // and have them safely wrap over when they go above 255
            let step = j.wrapping_add(51 * i as u8);
            data[i] = wheel(step);
        }
        let _ = neopixel.write(brightness(data.iter().cloned(), 32));
        delay.delay_ms(5u8);
    }
}
```

but maybe fully iterators teaches better.. is it as clear though?
```
const NUM_LEDS: usize = 5;

loop {
    for j in 0..255u8 {
        let _ = neopixel.write(brightness(
            (0..NUM_LEDS).map(|i| {
	        // stagger the color changes across all 5 leds evenly, 255/5=51
	        // and have them safely wrap over when they go above 255
                wheel(j.wrapping_add(51 * i as u8))
            }),
            32,
        ));

        delay.delay_ms(5u8);
    }
}
```

or maybe just go for 100% clarity and lose the inner loop ? Also no preallocation for better or worse
```
loop {
    for j in 0..255u8 {
        let colors = [
            // stagger the color changes across all 5 leds evenly, 255/5=51
            // and have them safely wrap over when they go above 255
            wheel(j),
            wheel(j.wrapping_add(51)),
            wheel(j.wrapping_add(102)),
            wheel(j.wrapping_add(153)),
            wheel(j.wrapping_add(204)),
        ];
        neopixel
            .write(brightness(colors.iter().cloned(), 32))
            .unwrap();
        delay.delay_ms(5u8);
    }
}
```

### PR DESCRIPTION
**Pull request by jacobrosenthal**
Closes #111 

Just realized we have hsv conversion in the smart_leds library were already bringing in. Anyone against removing the copy pasted wheel function everywhere? Starting in pygamer for this PR.

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
I guess the argument against is its slow to do on demand inside the write ... But Im not seeing any issues on 5 leds on 120mhz samd51...

**Comment by sajattack** [comment]
Yeah the wheel function was cribbed from some arduino code before we had hsv2rgb I think. Probably not necessary anymore

**Comment by jacobrosenthal** [comment]
Do you want me to PR the other wheel still in upstream? m4 devices each
have an example I think.

**Comment by sajattack** [comment]
Sure

**Pull request merged**
