### PR TITLE
Arduino Nano 33 IOT WiFi NINA SPI Master

### PR DESCRIPTION
**Pull request by olback**

### CODE REVIEW

**Comment by sajattack** [comment]
Might be worth adding an example too.

**Comment by olback** [comment]
> Might be worth adding an example too.

I'd love to but I don't have a working example with code from crates.io.

I got [wifi-nina](https://github.com/dflemstr/wifi-nina/) to work with some not-so-nice [modifications](https://github.com/olback/wifi-nina/tree/assertless-nocheck). I have since also found [wifinina](https://github.com/fionawhim/wifinina-rs) and [ublox-short-range-rs](https://github.com/BlackbirdHQ/ublox-short-range-rs) but not tested either of them.

**Comment by sajattack** [comment]
I think we can close this then if it's untested/unworking? Or draft until it works? Which would you prefer @olback?

**Comment by olback** [comment]
@sajattack It _is_ working but there isn't a great wifi-nina library. I have a [working fork](https://github.com/olback/wifi-nina/tree/assertless-nocheck) of the wifi-nina library. The spi helper implemented here works just fine.

**Comment by sajattack** [comment]
Yeah, if it's just a spi helper that doesn't actually pull in the rest of the wifi-nina features, I don't think it's very valuable. Someone can just set up a spi from the hal rather than the bsp.

**Pull request closed without merging**
