### PR TITLE
update svd2rust and form versions for PAC generation

### PR DESCRIPTION
**Pull request by TDHolmes**
# Summary
Only major changes were to DMA and ICM code which relied on traits on
registers, which got slightly tweaked in how they were implemented.
Other than that, it was an easy upgrade. Updated the update script name
to be a bit more clear in *what* it's updating

# Checklist
  - [x] `CHANGELOG.md` for the BSP or HAL updated
  - [x] All new or modified code is well documented, especially public items
  - [x] No new warnings or clippy suggestions have been introduced (see CI or check locally)

### CODE REVIEW

**Comment by bradleyharden** [comment]
The only HAL changes are to code from @jbeaurivage and @vcchtjader. Could you two check this?

**Comment by jbeaurivage** [comment]
Everything looks good on the `dmac` front :)

**Comment by TDHolmes** [comment]
I also want to make sure to run tests for `dmac` and `icm` on both my feathers before we merge just as a sanity. I haven't gotten a chance yet.
  - [ ] test `dmac` on `feather-m0` and `feather-m4`
  - [ ] test `icm` on `feather-m0` and `feather-m4`

**Comment by TDHolmes** [comment]
on HW tests looked good. Rebasing onto TOT

**Comment by vcchtjader** [comment]
The only change to `ICM` is changing one `Variant<x, y>` to an `Option<x>` for `URAT` register, this is the only use of `.variant()`.

Tested `icm` code on hardware and that runs :heavy_check_mark:

**Pull request merged**
