### PR TITLE
WIP: Add ATSAMD51P19A chip

### PR DESCRIPTION
**Pull request by blm768**
This PR adds the ATSAMD51P19A chip. I haven't thoroughly studied the datasheet yet, so there may well be some `#[cfg]` statements necessary, especially since this seems to the the first "P" chip to be added. What I've got so far should at least be a start, though.

### CODE REVIEW

**Comment by sajattack** [comment]
See #195

**Comment by blm768** [comment]
@sajattack: Could you use any help with the issues that are blocking support for this chip? I'm fairly new to embedded ARM development, but I should be able to pick up the necessary knowledge fairly quickly.

**Comment by sajattack** [comment]
You can join our matrix room (linked in this repo) and ask gkelly if there's anything you can help with.

**Comment by sajattack** [comment]
We are now ready to accept new chips.

**Pull request closed without merging**
