### PR TITLE
Add initial support for SAMD10C14A (SAMD10 family)

### PR DESCRIPTION
**Pull request by twopoint718**
- Add SVD files for samd10c14a and generate PAC

### CODE REVIEW

**Comment by sajattack** [comment]
Sorry, the SVD parser is currently being worked on so this isn't quite correct. Also, if you choose to redo this PR after #195 is closed, please add necessary changes to the HAL at the same time. Not much point in a PAC without a HAL here.

**Comment by twopoint718** [comment]
Ah okay, that's good to know. Yes, I will resubmit once #195 is closed. I'm still learning Rust and so the HAL is a little bit beyond me at the moment, but I'll see if I can find a collaborator. Thanks for the feedback!

**Comment by sajattack** [comment]
We are now ready to accept new chips.

**Comment by twopoint718** [comment]
🎉 I'll start working on it tonight. Thanks!

**Pull request closed without merging**
