### PR TITLE
Add ability to query frequency of configured SPI peripheral

### PR DESCRIPTION
**Pull request by TDHolmes**
Partially addresses #213 by adding a helper method to query the current configured frequency of the SPI peripheral. I also reduced the scope of some `unsafe` blocks, and made the usage of the `spi()` helper method more consistent in the code, as well as distinguishing between mutable/immutable access there.

### CODE REVIEW

**Comment by TDHolmes** [comment]
@BroderickCarlin can you try this branch out? I don't have any SPI stuff laying about to test this.

**Comment by TDHolmes** [comment]
I'm curious what you guys think of `spi()` and `spi_mut()`. Both return `&SERCOM`, but borrow `self` differently to show intent, as you can modify state with `&SERCOM`. I made the two variants so I could do
```rust
pub fn freq(&self, src_clock: &clock::$clock) -> Hertz { ... }
```

instead of
```rust
pub fn freq(&mut self, src_clock: &clock::$clock) -> Hertz { ... }
```

**Comment by TDHolmes** [comment]
@sajattack sorry for the churn, started playing around with refactoring common SPI logic out and I think I came up with a pretty good solution. I can pull this out into a separate later review if you want though. 

I wanted to move `set_baud` out too, but didn't want to change the existing API to make it happen (pass in source clock frequency instead of a reference to the clock)

**Comment by TDHolmes** [comment]
Fair enough, how about `CommonSpiInterface` or something?

**Comment by sajattack** [comment]
A bit long. Maybe Spi or CommonSpi

**Pull request merged**
