### PR TITLE
Swap to USB pad trait for thumv7em targets

### PR DESCRIPTION
**Pull request by ryankurte**
Supersedes https://github.com/atsamd-rs/atsamd/pull/362, related to https://github.com/atsamd-rs/atsamd/issues/363

An alternative approach that:
- Introduces `UsbPadD{m,p}` marker traits for implementation over USB pads
- Implements `UsbPadD{m, p}` marker trait over GPIO v1 and v2 types
- Adds `<Dm, Dp>` generic arguments to `UsbBus` and other types that default to existing (v1) pad types

This allows USB pad types to be overridden with something like: 
``` rust
// Override default USB GPIO types to v2
pub type UsbBus = atsamd_hal::usb::UsbBus<Pin<gpio::PA24, Alternate<H>>, Pin<gpio::PA25, Alternate<H>>>;
```

While (hopefully) maintaining compatibility with previous users of `UsbBus` and v1 GPIOs.

### CODE REVIEW

**Review by twitchyliquid64 — APPROVED** [review]
Awesomesauce!

**Comment by twitchyliquid64** [comment]
I thought you looked familiar! I was at Kawaiicon last year + distantly work with Grace's team! :grinning: 

Small world ^^

**Comment by ryankurte** [comment]
hah, wild how small it is sometimes ^_^

**Comment by twitchyliquid64** [comment]
(WRT the PR, LGTM but as mentioned in https://github.com/atsamd-rs/atsamd/issues/363#issuecomment-752292525 I'll wait till @bradleyharden has had a chance to look at it)

**Comment by bradleyharden** [comment]
@ryankurte,

From #362:

> I couldn't find an `.into()` bound that would work between v1 and v2, i might have just missed it though?

I added an implementation of `From` in both directions between `v1` and `v2`, but it missed the cut for the v0.11 release. @twitchyliquid64 just released v0.12, which now includes it. Instead of your current approach, you could make the `new` function generic with bounds like `Dm: Into<Pin<PA24, AlternateH>>`. That should be backwards compatible and accept both versions.

If you want to stick with a new trait for other reasons, you might want to make `crate::typelevel::Sealed` a super trait. That way, users won't be able to implement your new trait themselves, even if they try.

**Comment by twitchyliquid64** [comment]
The GPIO trait changes are merged in - is this ready to go @ryankurte / @bradleyharden or should we track one of the newer types?

**Comment by ryankurte** [comment]
I'd be happy either way, just haven't yet had a moment to revisit / rebase to use the `.into()` approach, whatever y'all prefer?

**Comment by ryankurte** [comment]
Went with the sealed approach which is a bit more complex but... also kindof nice in that you can click the trait and see the types it's implemented over more directly in the docs than looking via `.into()`.

**Comment by twitchyliquid64** [comment]
Thanks! Looks good to merge once we get CI green:

```
error[E0432]: unresolved import `cortex_m_0_6::peripheral::itm`
  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-0.5.10/src/peripheral/mod.rs:91:46
   |
91 | pub use cortex_m_0_6::peripheral::{cbp, fpb, itm, tpiu};
   |                                              ^^^ no `itm` in `peripheral`

```

**Comment by twitchyliquid64** [comment]
Hmmm i may have to fix this on master

**Comment by twitchyliquid64** [comment]
According to the embedded rust chat something mad derped in cortex-m, that might have been the issue

**Pull request merged**
