### PR TITLE
Make SPI Error support defmt::Format

### PR DESCRIPTION
**Pull request by henrikssn**
# Summary
Make SPI Error support the defmt::Format trait (behind the `defmt` feature)

# Checklist
  - [x] `CHANGELOG.md` for the BSP or HAL updated
  - [x] All new or modified code is well documented, especially public items
  - [x] No new warnings or clippy suggestions have been introduced (see CI or check locally)

### CODE REVIEW

**Comment by bradleyharden** [comment]
#467 will unify the implementation for the different chips, so that won't be an issue anymore. It might make sense to merge that one, since it's ready, and apply this PR to the new code.

**Comment by bradleyharden** [comment]
@henrikssn, you probably won't be able to rebase. Might be easier to just add it fresh. But #467 has been merged now

**Comment by henrikssn** [comment]
> @henrikssn, you probably won't be able to rebase. Might be easier to just add it fresh. But #467 has been merged now

Done, please take another look.

@TDHolmes now also added this for v1 SPI, thumbv7m and I2C.

**Comment by bradleyharden** [comment]
@henrikssn, I think you didn't pull the latest changes when you updated this PR, because your commits modify files in the `thumbv6m/sercom/v2` and `thumbv7em/sercom/v2` directories, which no longer exist.

If you update it, we can merge

**Comment by bradleyharden** [comment]
No worries. I didn't even notice this PR for the past 6 weeks, so...

**Comment by bradleyharden** [comment]
@henrikssn, still interested in following up with this? We're all busy, so 9 months isn't that long of a wait :p

**Pull request closed without merging**
