### PR TITLE
samd51 adc: init defines generic clock so adc0 and adc1 can be used at the same time

### PR DESCRIPTION
**Pull request by jacobrosenthal**
samd51 adc was hardcoding a single clock and crashing when both adc0 and adc1 were initialized at same time.

Moves clock selection to the adc init function instead. But this isnt very typestatey or safe and just moves the problem upstream. Perhaps we need a clock tree function call to replace  configure_gclk_divider_and_source to hand out generic clocks so users or subsystems cant reuse.

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
Offtopic but in same code, isnt panic formatting still a little troublesome to be guaranteed to be stripped. Should we have .expects over unwrap?

**Comment by sajattack** [comment]
I'm never sure when to use expect or unwrap or whatever. I've been told unwrap is a bit of a sin but maybe that's wrong.

**Comment by sajattack** [comment]
It's a little hairy to just assume the user passes in a 48mhz clock, I'm not sure what's better though.

**Comment by sajattack** [comment]
Maybe something like timerparams that outputs a particular samplerate the user requests.

**Comment by jacobrosenthal** [comment]
I think we need to impl all 11 clocks just with the GENA enums. Then have
user take them from clock tree and parcel them out to something like adc to
own, which can then some facade over configure_gclk_divider_and_source

**Comment by sajattack** [comment]
Sure, that works, but configurable samplerate would be good too.

**Comment by jacobrosenthal** [comment]
Opened a separate issue for the bigger discussion, I think this can be merged (when it passes travis)

**Pull request merged**
