### PR TITLE
hal: Switch from custom time traits to `embedded_time`

### PR DESCRIPTION
**Pull request by twitchyliquid64**
WIP

Anyone got a thumbv7-based board they can test the timers/pwm on to make sure the new divider calcuations are correct?

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
Took a look. PWM (tc4 tcc0) pygamer looked consistent. But timer tc3 panics 
```
18:51:35.272 panicked at 'internal error: entered unreachable code',
/home/jacob/Downloads/atsamd/hal/src/common/thumbv7em/timer.rs:107:22
```

I havent dug in further yet

**Comment by jacobrosenthal** [comment]
embedded-time got some nice cleanups after rtic started implementing it . Might be worth another look

**Comment by TDHolmes** [comment]
there's also now [`fugit`](https://docs.rs/fugit/latest/fugit/) which I like (it's a lot simpler), but it doesn't have the `Hz()`/`kHz()`/etc. helpers AFAIK.

**Comment by AfoHT** [comment]
Latest release [fugit v0.3.5](https://crates.io/crates/fugit/0.3.5) added support for `Hz, kHz` etc :D

**Comment by jbeaurivage** [comment]
Closed via #672.

**Pull request closed without merging**
