### PR TITLE
Add support for itsybitsy_m4

### LINKED ISSUE #89: ItsyBitsy M4 support
I've been eyeing the [ItsyBitsy M4](https://www.adafruit.com/product/3800) lately, because I already know I can deploy to M4 but I want something smaller. Are there any plans to add support for it?

I'm happy to do it myself. There's one slight issue, which is that I don't know how. I could go through the other M4 and M0 crates and try to adapt `itsybitsy_m0`, but I'm not sure if that'd miss something important or not, and I likely won't use enough of the HAL to catch subtler issues.

### PR DESCRIPTION
**Pull request by twitchyliquid64**
Fixes #89 

Examples tested on real hardware.

No examples for QSPI.

Includes code shopped around in #89 /w nic-hartley@, whom ive added as an author to the `Cargo.toml`. Ack/Nack @nic-hartley ?

### CODE REVIEW

**Comment by nic-hartley** [comment]
Have you tested this on a board? I burnt mine out (short in a USB voltage regulator gave it 120V briefly) or I'd do it.

**Comment by nic-hartley** [comment]
Cool! One last tiny change and I'm good with it -- my comment in the QSPIFlash impl should probably be removed or changed (maybe `TODO: add impl when QSPI support implemented` but feel free to bikeshed it)

Thanks!

**Comment by twitchyliquid64** [comment]
Doneskies :grin: :rocket:

**Comment by sajattack** [comment]
I'm not super happy about a special-purpose apa102 driver in this crate. Could you try bitbang-hal + apa102-spi?

**Comment by twitchyliquid64** [comment]
You mentioned it was broken in the issue?

Also: https://github.com/smart-leds-rs/apa102-spi-rs/blob/0dd2aeaec1806b79102639fc8748f63b209fe7a4/src/lib.rs#L57

Implementation seems to be missing the postamble?

**Comment by sajattack** [comment]
It was broken at one point but recent updates may have fixed it.

**Comment by sajattack** [comment]
Is this the postamble you're referring to? https://github.com/smart-leds-rs/apa102-spi-rs/issues/1

**Comment by twitchyliquid64** [comment]
Yes, but it looks like they've reached incorrect conclusions.

The postambles purpose is to drive the clock line (input -> output is delayed by one transition). The start of a new sequence of settings is identified by 32 or more consecutive zero bits, so any size postamble is valid.

**Comment by sajattack** [comment]
¯\_(ツ)_/¯

**Comment by sajattack** [comment]
image

**Comment by sajattack** [comment]
It works with bitbang-hal?

**Comment by twitchyliquid64** [comment]
I'm on the shuttle, I can test when I get home but I expect it will.

I dont understand why there are merge conflicts? upstream/master is up to date on my branch.

**Comment by sajattack** [comment]
Make sure you rebase instead of merge

**Comment by twitchyliquid64** [comment]
Rebased and successfully got the examples working. PTAL @sajattack !

**Comment by sajattack** [comment]
2 things:
1) You overwrote the main readme change to docs.rs
2) Why are you using bitbang-hal 0.2.2? 0.2.3 supports new input pins.

**Comment by sajattack** [comment]
Oh and what is spintimer? regular timers were too slow?

**Comment by twitchyliquid64** [comment]
> Oh and what is spintimer? regular timers were too slow?

It implements delays measured in cycles to implement the Timer and Periodic traits. Useful for when you dont want to use a timer or dont have any free.

I guess I should parameterize `dotstar()` to take a timer, so if people want to use a hardware timer they can?

> You overwrote the main readme change to docs.rs

Oopsies XD. Will fix.

> Why are you using bitbang-hal 0.2.2? 0.2.3 supports new input pins.

Copypasta. Will fix.

**Comment by sajattack** [comment]
Add your board to .travis.yml and change [OldInput|OldOutput]Pin to [Input|Output]Pin

**Comment by twitchyliquid64** [comment]
I can't seem to work out what the type is for the SPI pins, now that it needs some `E = Error` thing. My knowledge of rust is not good enough to work out whats going on here. Plain old `OutputPin` and `InputPin` isnt working, and niether are types like `OutputPin<Error = Pb3<Output<PushPull>>>,`

Any ideas how to get this to play ball, and what I should read up on?

**Comment by sajattack** [comment]
I think this maybe https://doc.rust-lang.org/book/ch19-03-advanced-traits.html#specifying-placeholder-types-in-trait-definitions-with-associated-types

**Comment by twitchyliquid64** [comment]
https://github.com/sajattack/bitbang-hal/blob/11b2a15cee043c6dc0db17cfd6e5b0985ec41b4a/src/spi.rs#L47

Fwict, E is a generic which is then used to declare an associated type? Whats the point of this + what am I meant to put there?

**Comment by sajattack** [comment]
It's because Pins can return errors, and we don't know what type of error. For atsamd-hal, the error type is `()`.

**Comment by twitchyliquid64** [comment]
Doesn't seem to work with `()` :(

```rust
        bitbang_hal::spi::SPI<
            InputPin<Error = ()>,
            OutputPin<Error = ()>,
            OutputPin<Error = ()>,
            SpinTimer,
        >,
```

```
   Compiling itsybitsy_m4 v0.1.0 (/home/xxx/projects/atsamd/boards/itsybitsy_m4)
error[E0277]: the size for values of type `(dyn embedded_hal::digital::v2::InputPin<Error=()> + 'static)` cannot be known at compilation time
   --> src/pins.rs:264:5
    |
264 | /     pub fn dotstar(
265 | |         self,
266 | |         port: &mut Port,
267 | |     ) -> apa102_spi::Apa102<
...   |
281 | |         Apa102::new_with_custom_postamble(spi, 4, false)
282 | |     }
    | |_____^ doesn't have a size known at compile-time
    |
    = help: the trait `core::marker::Sized` is not implemented for `(dyn embedded_hal::digital::v2::InputPin<Error=()> + 'static)`
    = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
    = note: required by `bitbang_hal::spi::SPI`

error[E0277]: the size for values of type `(dyn embedded_hal::digital::v2::OutputPin<Error=()> + 'static)` cannot be known at compilation time
   --> src/pins.rs:264:5
    |
264 | /     pub fn dotstar(
265 | |         self,
266 | |         port: &mut Port,
267 | |     ) -> apa102_spi::Apa102<
...   |
281 | |         Apa102::new_with_custom_postamble(spi, 4, false)
282 | |     }
    | |_____^ doesn't have a size known at compile-time
    |
    = help: the trait `core::marker::Sized` is not implemented for `(dyn embedded_hal::digital::v2::OutputPin<Error=()> + 'static)`
    = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
    = note: required by `bitbang_hal::spi::SPI`

error[E0277]: the trait bound `(dyn embedded_hal::digital::v2::InputPin<Error=()> + 'static): embedded_hal::digital::v1::InputPin` is not satisfied
   --> src/pins.rs:264:5
    |
264 | /     pub fn dotstar(
265 | |         self,
266 | |         port: &mut Port,
267 | |     ) -> apa102_spi::Apa102<
...   |
281 | |         Apa102::new_with_custom_postamble(spi, 4, false)
282 | |     }
    | |_____^ the trait `embedded_hal::digital::v1::InputPin` is not implemented for `(dyn embedded_hal::digital::v2::InputPin<Error=()> + 'static)`
    |
    = note: required by `bitbang_hal::spi::SPI`

error[E0277]: the trait bound `(dyn embedded_hal::digital::v2::OutputPin<Error=()> + 'static): embedded_hal::digital::v1::OutputPin` is not satisfied
   --> src/pins.rs:264:5
    |
264 | /     pub fn dotstar(
265 | |         self,
266 | |         port: &mut Port,
267 | |     ) -> apa102_spi::Apa102<
...   |
281 | |         Apa102::new_with_custom_postamble(spi, 4, false)
282 | |     }
    | |_____^ the trait `embedded_hal::digital::v1::OutputPin` is not implemented for `(dyn embedded_hal::digital::v2::OutputPin<Error=()> + 'static)`
    |
    = note: required by `bitbang_hal::spi::SPI`

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `itsybitsy_m4`.

To learn more, run the command again with --verbose.
```

**Comment by sajattack** [comment]
You still need to tell it which pin.

**Comment by sajattack** [comment]
I think maybe something like this `OutputPin<Pb3<Output<PushPull>>, Error=()>`

**Comment by twitchyliquid64** [comment]
Unfortunately not :/

```
[xxx@xxx]:~/projects/atsamd/boards/itsybitsy_m4> cargo build --examples --release
   Compiling itsybitsy_m4 v0.1.0 (/home/xxx/projects/atsamd/boards/itsybitsy_m4)
error[E0107]: wrong number of type arguments: expected 0, found 1
   --> src/pins.rs:269:22
    |
269 |             InputPin<Pb0<Input<PullUp>>, Error=()>,
    |                      ^^^^^^^^^^^^^^^^^^ unexpected type argument

error[E0107]: wrong number of type arguments: expected 0, found 1
   --> src/pins.rs:270:23
    |
270 |             OutputPin<Pb3<Output<PushPull>>, Error = ()>,
    |                       ^^^^^^^^^^^^^^^^^^^^^ unexpected type argument

error[E0107]: wrong number of type arguments: expected 0, found 1
   --> src/pins.rs:271:23
    |
271 |             OutputPin<Pb2<Output<PushPull>>, Error = ()>,
    |                       ^^^^^^^^^^^^^^^^^^^^^ unexpected type argument

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0107`.
error: Could not compile `itsybitsy_m4`.

To learn more, run the command again with --verbose.
```

I've also tried setting the `Error` to various types from the spi crate as well as `u8`, to no avail.

I also cant see any similar usage online based on this search: https://github.com/search?l=Rust&q=embedded_hal%3A%3Adigital%3A%3Av2%3A%3AInputPin&type=Code

**Comment by sajattack** [comment]
Get rid of OutputPin and just to Pb3?

**Comment by twitchyliquid64** [comment]
Nope, getting trait not satisfied errors :/

I think I've worked out whats going on:
```shell

[jsonp@jsonp-glaptop]:~/projects/atsamd/boards/itsybitsy_m4> cat ~/.cargo/registry/src/github.com-1ecc6299db9ec823/bitbang-hal-0.2.3/src/spi.rs 
pub use embedded_hal::spi::{MODE_0, MODE_1, MODE_2, MODE_3};

use embedded_hal::digital::{InputPin, OutputPin};
use embedded_hal::spi::{FullDuplex, Mode};
use embedded_hal::timer::{CountDown, Periodic};
use nb::block;

<snip>
```

`0.2.3` is the latest available, but 0.2.4 is the one with the digital::v2 implementation. Can you push 0.2.4 to the crate thingyboi?

**Comment by sajattack** [comment]
I released 0.2.4 as 0.3.0 because I'm pretty sure that's better semver.

**Comment by twitchyliquid64** [comment]
Yep yep sounds good. I'll refactor and test sometime tonight.

**Comment by sajattack** [comment]
Could you move spintimer to timer.rs instead of delay.rs? And add `FEATURES="--features=unproven"` to .travis.yml

**Comment by twitchyliquid64** [comment]
PTAL @sajattack ! :rocket:

**Comment by twitchyliquid64** [comment]
actually one sec

**Comment by twitchyliquid64** [comment]
kek

**Comment by sajattack** [comment]
LGTM

**Pull request merged**
