### PR TITLE
Add missing register field TCn.COUNTn.CTRLA.DMAOS for D5x/E5x devices

### LINKED ISSUE #147: SAMD5x/E5x PACs missing register field TC.CTRLA.DMAOS
Another SVD mismatch with the reference manual.

Pretty much what it says on the tin. The `DMAOS` field of the `CTRLA` register for TC peripherals is not present in the SVD files for all processors in the SAMD5x/E5x family, but is present in the Reference Manual. All possible TC mode configurations (`COUNT8`, `COUNT16`, `COUNT32`) in the associated PACs are missing this field.

### PR DESCRIPTION
**Pull request by jessebraham**
Closes #147.

(I had to learn XSL to do this; I think it's correct but if somebody could verify that'd be appreciated)

### CODE REVIEW

**Comment by sajattack** [comment]
Can you make a simple program for me to test this on d51?

**Comment by jessebraham** [comment]
What specifically would you like to see tested, just that the `DMAOS` field can be written to and read from? All I can do is confirm compilation at this point, still waiting on my D51.

**Comment by sajattack** [comment]
Yeah I guess that works. I can test for you.

**Comment by jessebraham** [comment]
If you don't mind that'd be awesome.

**Comment by sajattack** [comment]
https://gist.github.com/sajattack/8deca7c0a96b4390250f6d31fb18508f#file-dmaos_test-rs-L86
test fail

**Comment by sajattack** [comment]
Helps if you turn on the MCLK for the peripheral you're writing to :P

**Pull request merged**
