### PR TITLE
Fix gpio::v2 PORT access functions and add a bsp_pins macro

### LINKED ISSUE #364: Aliasing GPIO names at the board level still available for after v2 Refactor?
One thing I did notice during my migration here: #363  is whether or not now there's a way to alias the names of the pins for specific boards. Is that still possible or with the refactor that won't work anymore?

### PR DESCRIPTION
**Pull request by bradleyharden**
See discussion in #363.

@jaredwolff, could you give this a try and see what you like/don't like? I'd like to get some feedback on it before merging.

Edit: closes #364

### CODE REVIEW

**Comment by jaredwolff** [comment]
@bradleyharden 

Maybe I'm doing something wrong here. For some reason its complaining about the `paste` function:

```
error: cannot find macro `paste` in this scope
  --> src/lib.rs:28:1
   |
28 | / bsp_pins!(
29 | |     #[cfg(feature = "unproven")]
30 | |     PA23 { name: led_pass }
31 | | );
   | |__^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

I'm importing the macro as: `use hal::bsp_pins;`

**Comment by jaredwolff** [comment]
One thing that would be immensely helpful is the inclusion of what you're importing in your documentation code. For example:

```
use paste::paste;
use hal::bsp_pins;

bsp_pins!(
    #[cfg(feature = "unproven")]
    PA24 {
        name: led_pass,
        aliases: {
            AlternateH: LedPass,
            #[cfg(feature = "usb")]
            AlternateM: UsbPin
        }
    }
);
```

**Comment by jaredwolff** [comment]
Got it working on rtic:

```rust
#![deny(unsafe_code)]
#![no_main]
#![no_std]

extern crate circuitdojo_tester as hal;
use panic_halt as _;

use hal::clock::GenericClockController;

use hal::delay::Delay;
use hal::prelude::*;
use hal::Pins;

#[rtic::app(device = hal::pac, peripherals = true)]
const APP: () = {
    struct Resources {
        led_pass: hal::LedPass,
        delay: Delay,
    }
    #[init()]
    fn init(cx: init::Context) -> init::LateResources {
        let mut peripherals = cx.device;
        let mut clocks = GenericClockController::with_external_32kosc(
            peripherals.GCLK,
            &mut peripherals.PM,
            &mut peripherals.SYSCTRL,
            &mut peripherals.NVMCTRL,
        );
        let pins = Pins::new(peripherals.PORT);
        let led_pass = pins.led_pass.into_push_pull_output();

        let delay = Delay::new(cx.core.SYST, &mut clocks);

        init::LateResources { led_pass, delay }
    }
    #[idle(resources=[led_pass, delay])]
    fn idle(cx: idle::Context) -> ! {
        loop {
            let _ = cx.resources.led_pass.toggle();
            cx.resources.delay.delay_ms(500u32);
        }
    }
};
```

The pin alias worked like a charm.

**Comment by bradleyharden** [comment]
> One thing that would be immensely helpful is the inclusion of what you're importing in your documentation code.

Paste shouldn't have been required. That's a mistake on my part. I'll find a way to use the re-exported version in the HAL. I can add a line to the example to show how to import the macro.

Also, this isn't really directed at you but more at everyone. I don't like how we use "hal" as the short name for Embedded HAL, ATSAMD-HAL and some BSPs. It's *really* confusing. I think we ought to start trying to change that.

**Comment by jaredwolff** [comment]
>Also, this isn't really directed at you but more at everyone. I don't like how we use "hal" as the short name for Embedded HAL, ATSAMD-HAL and some BSPs. It's really confusing. I think we ought to start trying to change that.

I'm just using it the way it was done in the examples. If you have suggestions that make it more sane I'm all ears.

**Comment by bradleyharden** [comment]
I made the requested changes. If @jaredwolff is satisfied and nobody else has any feedback, I think we can merge this.

**Comment by jaredwolff** [comment]
Nice. I'll play with it to make sure there aren't any new problems.

**Comment by bradleyharden** [comment]
Thanks.

This should close #364.

**Comment by jaredwolff** [comment]
So far so good. I had to add some compatibility to the ADC and USB drivers Otherwise no issues with importing/using v2. Thanks again @bradleyharden!

**Comment by bradleyharden** [comment]
Cool. Thanks for testing.

I actually just discovered `$crate` for use in macros today. It solves a problem I had when writing the `bsp_pins` macro, so I'll probably modify it. But that should he completely transparent to users.

**Comment by jaredwolff** [comment]
Oh nice! Never heard of that either. Does it affect how you were importing the crates in the macro? Curious what it will look like afterwards.

**Comment by bradleyharden** [comment]
@jaredwolff, see the latest implementation of `bsp_pins` in #410 for the new macro using `$crate`. It's not much of a difference. It just means I don't have to refer to `atsamd_hal` by name.

**Pull request merged**
