### PR TITLE
Gpio type erasure

### PR DESCRIPTION
**Pull request by Sympatron**
Implemented `downgrade` for gpio pins to solve #203.
Currently only thumbv7m support, but I think it could be ported to thumbv6m easily.

### CODE REVIEW

**Comment by sajattack** [comment]
Looks great! Can you explain the naming of the pin_x and pin_xx macros? It's not terribly clear what it means from the name.

**Comment by sajattack** [comment]
Also, could you document the downgrade method since it is public?

**Comment by Sympatron** [comment]
Just realized that the current implementation of `Pxx` is buggy. I'll try to fix it.

**Comment by bradleyharden** [comment]
@Sympatron, now that #302 has been merged, will the `DynPin` API satisfy your needs?

**Comment by Sympatron** [comment]
Yes this can be closed now.

**Pull request closed without merging**
