### PR TITLE
Update to latest method of bsp/hal import style and rust edition

### PR DESCRIPTION
**Pull request by TDHolmes**
As promised @jbeaurivage, here's my crack at updating everything to our latest way of doing things.

### CODE REVIEW

**Comment by bradleyharden** [comment]
Did you do all of this by hand?!

**Comment by TDHolmes** [comment]
Haha, no most of it was regex find and replace

**Comment by jbeaurivage** [comment]
While we're at it, how do you feel about trying to get rid of all references to `target_device`? The HAL already aliases it as `pac`, and we're eventually (soon) phase out `target_device` in favour of `pac`.

**Comment by TDHolmes** [comment]
If the PR wasn't massive enough yet haha. Was pretty easy find/replace though.

**Pull request merged**
