### PR TITLE
I2c bus hangs

### PR DESCRIPTION
**Pull request by jacobrosenthal**
Im having issues with the lis3dh where its freezing up the bus. Im not sure its recoverable, I'll keep working on it. But it shouldnt just hang the device forever. I looked and sure enough adafruit's arduino core has a similar checking which I've cribbed here.

https://github.com/adafruit/ArduinoCore-samd/blob/master/cores/arduino/SERCOM.cpp#L545

Probably should go on all devices, but ill let the bikeshedding start first on if Buserror is the right error, etc first.

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
With this all I need is a clean way to signal via led that theres a panic so the user can click the rest button :)

**Comment by jacobrosenthal** [comment]
The stuff to bikeshed here is, this changes waiting forever for the bus to be available to making the user look for.. say a BusError to retry in user code. Im not sure why, but hal could retry 5 or 100 or 1000 times for the user first for some kind of middle ground

**Comment by sajattack** [comment]
I think just returning an error is fine. User code can choose to retry.

**Comment by jacobrosenthal** [comment]
Rebased

I still dont have a feel for if we consider this breaking. There could be a device out there that was idle or busy for 1 or 1000 cycles through the loop but then recovered. So were breaking those devices by erroring on the first check.

Side note: for me, this error is unrecoverable. Were already resetting the i2c sercom on new and thats not shaking up the device. The pygamer doesnt put the device's power pin to a gpio so I cant reset it otherwise. In practice this fits well with my panic_led feature because the device will basically come up panic'ed which is shown on the led and I have users just toggle the power switch when that happens.

**Review by twitchyliquid64 — APPROVED** [review]

**Pull request merged**
