### PR TITLE
Add initial support for SAMD11C14A

### PR DESCRIPTION
**Pull request by jessebraham**
This should add initial support for the aforementioned device. Couldn't get the USB module to build so it is not included at this time, but everything else from `hal/src/samd21` should be there. Only really tested with a blinky app so far, but that confirms multiple peripherals are functioning so that's a good sign.

The feature gating in `hal/src/lib.rs` could probably be a bit cleaner, but this should work for the time being. When/if more devices get added it may be worth adding a `samd21` feature as well or something.

I haven't added anything to `travis.yml` regarding the new device as there are not currently any board crates that use it. Not sure if this is an issue or if it's okay for the time being.

If I've omitted anything or anything needs fixing just let me know.

### CODE REVIEW

**Comment by sajattack** [comment]
I would like to see more testing done before merging

**Comment by jessebraham** [comment]
Sounds good, just wanted to get the ball rolling. I'll try to get a bit of testing done this evening or tomorrow if possible.

**Comment by sajattack** [comment]
Pay special attention to sercom padout

**Comment by jessebraham** [comment]
Still working on this, slowly.

I've additionally tested Timers and the ADC, both appear to be functioning properly to the best of my knowledge. Working on testing PWM and UART next, will update when I have them working.

**Comment by sajattack** [comment]
Great, thanks

**Comment by jessebraham** [comment]
I got the UART working this morning, tested `SERCOM0` and `SERCOM1`.

I'm trying to figure out why PWM isn't working currently. I haven't looked at I2C or SPI at all yet, but those would be next and (for now) the last tests.

I've just been duplicating examples from other boards for my testing. Just to recap, so far I've replicated and validated:

- `feather_m0/examples/blinky_basic.rs`
- `metro_m4/examples/timer.rs`
- `feather_m0/examples/adc.rs`
- `metro_m4/examples/serial.rs`

Anything else you'd like to see done other than what's mentioned in this comment?

**Comment by sajattack** [comment]
That's probably enough I think. Anything else you'd like to add?

**Comment by jessebraham** [comment]
I would eventually like to get USB working as well, but I think I'll wait to do so in another PR. I think what I have is a decent base for the time being.

Since I'm just using a chip on a breadboard I've created a `samd11_bare` "board", which I have now added and included in the Travis config. It's a bit hacky, so if you'd like any changes made to this let me know, wasn't quite sure how else to approach testing.

I took a look through [awesome-embedded-rust](https://github.com/rust-embedded/awesome-embedded-rust) and I own a couple of devices with I2C drivers implemented, so I'm hoping to have that working sometime this weekend. Unfortunately it doesn't appear I have anything with a SPI driver written at this point in time, I hope that's not a problem.

**Comment by sajattack** [comment]
With SERCOMs, if Serial works, I2C and SPI likely will too.

**Comment by sajattack** [comment]
16K flash is pretty smol. Try telling travis to build in release mode.

**Comment by jessebraham** [comment]
Yes that seems to be the issue, running without `--release` causes the linker error locally for me too.

I'm not super familiar with Travis unfortunately, am I able to add `--release` to the entry within `env` somehow, or do I need to specify it under `script` where `cargo build` gets called?

**Comment by sajattack** [comment]
Yeah I see what you mean, it will require a few changes to our current travis setup. If you add me to your repo I can take care of it.

**Comment by jessebraham** [comment]
I've added you as a collaborator, thanks!

**Comment by sajattack** [comment]
I'm good to merge if you are.

**Comment by jessebraham** [comment]
Sounds great, thanks again for the help.

**Pull request merged**
