### PR TITLE
Add support for Wio Lite MG126

### PR DESCRIPTION
**Pull request by hmax**
Adds initial support for Wio Lite MG126 (no radio-specific things atm), based on boards/arduino_mkrzero

### CODE REVIEW

**Comment by jessebraham** [comment]
Thanks for this! Apologies for taking so long to review it.

Overall this is looking pretty good, there are just a couple small changes I'd like made first. Could you please:
* add the missing `boards/wio_lite_mg126/.cargo/config` file (to specify the target)
* add an entry to `.travis.yml` to build this board's examples

**Comment by hmax** [comment]
No worries, there's no hurry in this PR.
I think I've fixed all of the issues and it should be good now

**Review by jessebraham — APPROVED** [review]
Thanks for getting those changes made! I'm happy to merge this as-is, thank you again for your contributions.

**Comment by jessebraham** [comment]
@hmax Sorry I keep forgetting to ask people about this! 😁 

Would you be okay with me adding your username to our [board owner list](https://github.com/atsamd-rs/atsamd/wiki/Board-owner-list) just in case we need somebody to do some testing for this board? No sweat if you're not interested of course!

**Comment by hmax** [comment]
@jessebraham sure, I'd be glad to help

**Comment by jessebraham** [comment]
@hmax great, thanks! This crate is now available on [crates.io](https://crates.io), I had forgotten to publish it when I merged.

**Pull request merged**
